Section 2.6:  Linear Systems of Equations

Basic Solving of Ax=b

In [16]:
import numpy as np

# define a 3x3 matrix
A = np.array([[1,1,1],[1,2,4],[1,3,9]])
b = np.array([[1],[-1],[1]])

x = np.linalg.solve(A,b)

display(x)

array([[ 7.],
       [-8.],
       [ 2.]])

LU Decomposition of a matrix

In [7]:
import scipy
import scipy.linalg

# the LU decomposition
P, L, U = scipy.linalg.lu(A)

# solving with the decomposition
b2 = np.matmul(P, b)
y = np.linalg.solve(L,b2)
x = np.linalg.solve(U,y)

display(P)
display(L)
display(U)

display(y)
display(x)


array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

array([[1. , 0. , 0. ],
       [1. , 1. , 0. ],
       [1. , 0.5, 1. ]])

array([[ 1.,  1.,  1.],
       [ 0.,  2.,  8.],
       [ 0.,  0., -1.]])

array([[ 1.],
       [ 0.],
       [-2.]])

array([[ 7.],
       [-8.],
       [ 2.]])

In [20]:
import numpy as np

x = np.array([0, 0], dtype=float)

for j in range(1000):
    J = np.array([[2 + 3*x[0]**2, 1],
                  [1 + x[1] + np.exp(x[0]), x[0]]])
    f = np.array([2*x[0] + x[1] + x[0]**3, x[0] + x[0]*x[1] + np.exp(x[0])])

    if np.linalg.norm(f) < 10**(-6):
        break

    df = -np.linalg.solve(J, f)
    x = x + df

print("x =", x)


x = [-0.37830658  0.81075482]


In [17]:
import numpy as np
from scipy.optimize import fsolve

def system(x):
    f = np.array([2*x[0] + x[1] + x[0]**3,
                  x[0] + x[0]*x[1] + np.exp(x[0])])
    return f

x_initial_guess = np.array([0, 0])

x_solution = fsolve(system, x_initial_guess)

print("x =", x_solution)


x = [-0.37830658  0.81075482]
