Section 2.1:  Linear Systems of Equations

Basic Solving of Ax=b

In [4]:
import numpy as np

# define a 3x3 matrix
A = np.array([[1,1,1],[1,2,4],[1,3,9]])
b = np.array([[1],[-1],[1]])

x = np.linalg.solve(A,b)

display(x)

array([[ 7.],
       [-8.],
       [ 2.]])

LU Decomposition of a matrix

In [9]:
import scipy
import scipy.linalg

P, L, U = scipy.linalg.lu(A)

b2 = np.matmul(P, b)
y = np.linalg.solve(L,b2)
x = np.linalg.solve(U,y)

display(P)
display(L)
display(U)

display(y)
display(x)


array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

array([[1. , 0. , 0. ],
       [1. , 1. , 0. ],
       [1. , 0.5, 1. ]])

array([[ 1.,  1.,  1.],
       [ 0.,  2.,  8.],
       [ 0.,  0., -1.]])

array([[ 1.],
       [ 0.],
       [-2.]])

array([[ 7.],
       [-8.],
       [ 2.]])