Section 1.1:  Vectors and Matrices

In [2]:
import numpy as np

# ways to make a row vector
x1 = [1, 3, 2]  
x2 = np.array([1,3,2])  
x3 = np.matrix([1,3,2])

display(x1)
display(x2)
display(x3)

[1, 3, 2]

array([1, 3, 2])

matrix([[1, 3, 2]])

In [3]:
# ways to make a column vector
x1 = np.matrix([[1], [3], [2]])
x2 = np.array([[1], [3], [2]])

display(x1)
display(x2)

matrix([[1],
        [3],
        [2]])

array([[1],
       [3],
       [2]])

In [4]:
# make a vector over a range

#   generic structure np.arange(beginning, end+h, step-size h)


x1 = np.arange(0,10.1,1)   # go from 0 to 10 in steps of 1
x2 = np.arange(0,11,2)
x3 = np.arange(0,1.2,0.2)
x4 = np.arange(0,9,2)
x5 = np.arange(0,5)        # if h is not specified, then h=1

display(x1)
display(x2)
display(x3)
display(x4)
display(x5)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

array([ 0,  2,  4,  6,  8, 10])

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

array([0, 2, 4, 6, 8])

array([0, 1, 2, 3, 4])

Constructing Matrices

In [6]:
# define a 3x3 matrix
A = np.array([[1,3,2],[5,6,7],[8,3,1]]) 
A2 = np.array([[1,3,2],
               [5,6,7],
               [8,3,1]]) 

x1 = A[1,2]  # this gives the 2nd row, 3rd column value (rememer that indexing starts at 0)
x2 = A[1,:]  # access the entire 2nd row
x3 = A[:,2]  # access the entire 3rd column


xp = A[1,0:2]

display(A)
display(A2)
display(x1)
display(x2)
display(x3)

array([[1, 3, 2],
       [5, 6, 7],
       [8, 3, 1]])

array([[1, 3, 2],
       [5, 6, 7],
       [8, 3, 1]])

7

array([5, 6, 7])

array([2, 7, 1])

In [8]:
# More complicated 4x4 matrix
B = np.array([[1,7,9,2],[2,3,3,4],[5,0,2,6],[6,1,5,5]])

x1 = B[1:3,1] #  extract 2nd and 3rd row of column 2
x2 = B[3,1:]  #  extract 2nd through last column of row 4

C = B[:-1,1:4]  # extract matrix of 2nd-4th columns and first to next to last rows

D = ( B[0,1:4], B[0:3,2].T ) # extract 2nd-4th column of first row and put it on top of 3rd column, 1st-3rd row transposed

display(B)
display(x1)
display(x2)
display(C)
display(D)


array([[1, 7, 9, 2],
       [2, 3, 3, 4],
       [5, 0, 2, 6],
       [6, 1, 5, 5]])

array([3, 0])

array([1, 5, 5])

array([[7, 9, 2],
       [3, 3, 4],
       [0, 2, 6]])

(array([7, 9, 2]), array([9, 3, 2]))

In [7]:
# Complex matrices and transpose

x = np.array([3+2j,1,8])

x1 = x.T  # transpose
x2 = np.conj(x)  # conjugate

print(x)
print(x1)
print(x2)

[3.+2.j 1.+0.j 8.+0.j]
[3.+2.j 1.+0.j 8.+0.j]
[3.-2.j 1.-0.j 8.-0.j]


In [10]:
# vector manipulations

x = np.array([-1, 2, 3, 5, -2])

x1 = [(x>0)]

y1 = (x > 0) * 1
y2 = (x > 0) * x
y3 = (x > 0) * 3

display(x)
display(x1)
display(x2)

print(y1)
print(y2)
print(y3)

array([-1,  2,  3,  5, -2])

[array([False,  True,  True,  True, False])]

array([3.-2.j, 1.-0.j, 8.-0.j])

[0 1 1 1 0]
[0 2 3 5 0]
[0 3 3 3 0]
