Making Functions in python

In [3]:
import numpy as np

def myfun(x):    
    y = x**3 + np.sin(x)
    return y


# single input to the function
out1 = myfun(1)

# vector of inputs to the function
x = np.arange(0,11,1)
out2 = myfun(x)

display(out1)
display(out2)

1.8414709848078965

array([  0.        ,   1.84147098,   8.90929743,  27.14112001,
        63.2431975 , 124.04107573, 215.7205845 , 343.6569866 ,
       512.98935825, 729.41211849, 999.45597889])

In [5]:
def funcA(x,A):    
    B = A**2 + np.cos(A)
    fA = np.sin(B*x)
    
    return fA,B


# multiple inputs and outputs for a function
out3 = funcA(3,2)
fA, B = funcA(np.array([3, 4, 5]), 2)
display(out3)
display(fA)
display(B)


(-0.970375821283421, 3.5838531634528574)

array([-0.97037582,  0.98041359, -0.80179334])

3.5838531634528574

In [6]:
import numpy as np

def func(x):
    A = float(input('A= '))
    return np.sin(A * x)

# Example usage
x = np.array([1, 2, 3, 4, 5])
result = func(x)
print(result)

        

A= 5
[-0.95892427 -0.54402111  0.65028784  0.91294525 -0.13235175]


In [8]:
reply = input('Do you want more? Y/N [Y]: ')
if not reply:
    reply = 'Y'

print(reply)

Do you want more? Y/N [Y]: 
Y


In [10]:
display('hello world')

'hello world'

In [11]:
x = 'hello world'
display(x)

'hello world'